Adjusting "Shirakami Fubuki" title.
nevrending/foob pull request #1
Opened 2021-05-06 12:17 UTC by bempfoobq052021

Changes in custom.css : .presentation-title, .footer-nav line-height (accomodating mobile version).
Changes in index.html : 
<h1> to <span> (accomodating mobile version) 
style=font moved to custom.css
line-height added to adjust <span> to look more natural like <h1>

2021-05-07 16:20 UTC, nevrending requested changes
Hi there! Thanks for your PR. It makes the mobile view looks better.

![image](https://user-images.githubusercontent.com/4745298/117479370-99374b80-afa3-11eb-9602-beab4f922820.png)

Just a couple of things:
- We use space for indentation instead of tabs
- The `span` tag that replaced `h1` hasn't been closed
- Footer CSS fixed mobile, but makes desktop looks misaligned (see below).

![image](https://user-images.githubusercontent.com/4745298/117479582-d8659c80-afa3-11eb-9781-744489846c19.png)

I've put in some inline comments that you can directly commit or you can make a commit that contains all of them, whichever works best for you.

2021-05-07 16:20 UTC, nevrending commented on assets/css/custom.css
> +	min-width: 320px;
```suggestion
    min-width: 320px;
```

2021-05-07 16:20 UTC, nevrending commented on assets/css/custom.css
> +	line-height: 6rem;
```suggestion
    font-size: 5.5rem;
    background: linear-gradient(180deg,#fff 35%,#8fb2c3);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    line-height: 6rem;
```

2021-05-07 16:20 UTC, nevrending commented on assets/css/custom.css
> +	line-height: 5rem;
```suggestion
    font-size: 3.5rem;
    line-height: 5rem;
```

2021-05-07 16:20 UTC, nevrending commented on index.html
> +          <span class="presentation-title">Shirakami Fubuki</h1>
Tag has not been closed properly.

```suggestion
          <span class="presentation-title">Shirakami Fubuki</span>
```

2021-05-08 10:39 UTC, bempfoobq052021 commented on index.html
> +          <span class="presentation-title">Shirakami Fubuki</h1>
Whoops. I'll accept this immediately.

2021-05-08 10:40 UTC, bempfoobq052021 commented on assets/css/custom.css
> +	line-height: 5rem;
Looks good to me~! Thanks for the fix!

2021-05-08 10:41 UTC, bempfoobq052021 commented on assets/css/custom.css
> +	line-height: 6rem;
Looks good to me~!

2021-05-08 11:32 UTC, bempfoobq052021 commented
On this problem : 
Footer CSS fixed mobile, but makes desktop looks misaligned (see below).

Fixed by changing `<span class="copyright"> to <p class="copyright" style="line-height:20pt">`
I use &nbsp for the spaces though.

2021-05-11 05:51 UTC, nevrending approved these changes
I'll accept this PR for now, since the hero fix is good, and work on the remaining issues on a separate commit.

Thanks again for your contribution!

2021-05-11 05:51 UTC, nevrending commented on index.html
> -  <script src="assets/js/theme.min.js?v=2.2.0"></script>
These should not be removed as they enabled the dropdown menu and stuffs.

2021-05-11 05:51 UTC, merged